version: '3.8'

services:
  radio-listener:
    build: .
    container_name: radio-listener
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./clips:/app/clips
      - ./config:/app/config
    restart: unless-stopped